name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  pre-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Slack Notify
        # You may pin to the exact commit or the version.
        # uses: rtCamp/action-slack-notify@ae4223259071871559b6e9d08b24a63d71b3f0c0
        uses: rtCamp/action-slack-notify@v2.1.2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: testing-slack-integration
          SLACK_MESSAGE: Testing environment deployment process - pre-deploy
          SLACK_COLOR: FF00EF
          MSG_MINIMAL: true
          SLACK_FOOTER: Powered by ~hopes and dreams~ trial and error.
          
  stage-deploy:
      runs-on: ubuntu-latest
      environment: staging
      needs: [pre-deploy]

      steps:
        - name: Slack Notify
          # You may pin to the exact commit or the version.
          # uses: rtCamp/action-slack-notify@ae4223259071871559b6e9d08b24a63d71b3f0c0
          uses: rtCamp/action-slack-notify@v2.1.2
          env:
            SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
            SLACK_CHANNEL: testing-slack-integration
            SLACK_MESSAGE: Testing environment deployment process - stage deploy
            SLACK_COLOR: 0010FF
            MSG_MINIMAL: true
            SLACK_FOOTER: Powered by ~hopes and dreams~ trial and error.
          
  prod-deploy:
      runs-on: ubuntu-latest
      environment: production
      needs: [stage-deploy]

      steps:
        - name: Slack Notify
          # You may pin to the exact commit or the version.
          # uses: rtCamp/action-slack-notify@ae4223259071871559b6e9d08b24a63d71b3f0c0
          uses: rtCamp/action-slack-notify@v2.1.2
          env:
            SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
            SLACK_CHANNEL: testing-slack-integration
            SLACK_MESSAGE: Testing environment deployment process - prod deploy
            SLACK_COLOR: 56FF00
            MSG_MINIMAL: true
            SLACK_FOOTER: Powered by ~hopes and dreams~ trial and error.
